version: "3.9"

services:
  hospital-app:
    build:
      context: .
    container_name: hospital_management_system
    ports:
      - "8080:80"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
    volumes:
      - .:/app
    restart: unless-stopped
